version = 1

# Code
[[annotations]]
path = [
  "*.lua",
  "README.md",
]
SPDX-FileCopyrightText = [
  "2026 Sheriff U3",
  "2017 jordan4ibanez"
]
SPDX-License-Identifier = "MIT"

# Media
[[annotations]]
path = [
  "*/*.glb",
  "*/*.png",
  "*/.dev/**",
]
SPDX-FileCopyrightText = [
  "2026 Sheriff U3"
]
SPDX-License-Identifier = "MIT"

# Config files
[[annotations]]
path = [
  ".*/**",
  ".*",
  "mod.conf",
  "settingtypes.txt",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"